{*
$Id: sitemap.tpl,v 1.4 2010/06/08 06:17:41 igoryan Exp $
vim: set ts=2 sw=2 sts=2 et:
*}
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="{$SkinDir}/modules/XML_Sitemap/style.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.google.com/schemas/sitemap/0.84 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
//<![CDATA[#Generated by 'X-SEO: XML Sitemap' generator by Qualiteam software, http://www.qtmsoft.com/, http://www.x-cart.com/ //]]>
{section name="i" loop=$xmlmap_items}
{strip}
  <url>
    <loc>
      {$xmlmap_items[i].loc}
    </loc>
    {if $xmlmap_items[i].lastmod ne ""}
    <lastmod>
      {$xmlmap_items[i].lastmod}
    </lastmod>
    {/if}
    <changefreq>
      {$xmlmap_items[i].changefreq}
    </changefreq>
    <priority>
      {$xmlmap_items[i].priority}
    </priority>
  </url>
{/strip}
{/section}
</urlset>
