INSERT INTO xcart_states (state, code, country_code) VALUES ('Alabama','AL', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Alaska','AK', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Arizona','AZ', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Arkansas','AR', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Armed Forces Americas','AA', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Armed Forces Europe, Middle East & Canada','AE', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Armed Forces Pacific','AP', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('California','CA', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Colorado','CO', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Connecticut','CT', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Delaware','DE', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('District of Columbia','DC', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Florida','FL', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Georgia','GA', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Guam','GU', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Hawaii','HI', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Idaho','ID', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Illinois','IL', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Indiana','IN', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Iowa','IA', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Kansas','KS', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Kentucky','KY', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Louisiana','LA', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Maine','ME', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Maryland','MD', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Massachusetts','MA', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Michigan','MI', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Minnesota','MN', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Mississippi','MS', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Missouri','MO', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Montana','MT', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Nebraska','NE', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Nevada','NV', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('New Hampshire','NH', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('New Jersey','NJ', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('New Mexico','NM', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('New York','NY', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('North Carolina','NC', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('North Dakota','ND', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Ohio','OH', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Oklahoma','OK', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Oregon','OR', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Pennsylvania','PA', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Puerto Rico','PR', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Rhode Island','RI', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('South Carolina','SC', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('South Dakota','SD', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Tennessee','TN', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Texas','TX', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Utah','UT', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Vermont','VT', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Virgin Islands','VI', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Virginia','VA', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Washington','WA', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Virginia','WV', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Wisconsin','WI', 'US');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Wyoming','WY', 'US');

