INSERT INTO xcart_states (state, code, country_code) VALUES('Almeria','AM','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Alicante','AA','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Alava','AL','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Albacete','AB','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Asturias','AS','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Avila','AV','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Badajoz','BA','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Illes Balears','IB','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Barcelona','BC','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Burgos','BU','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Caceres','CC','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Cadiz','CD','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Cantabria','CT','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Castellon','CS','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Ceuta','CE','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Ciudad Real','CR','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Cordoba','CO','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Cuenca','CU','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Gerona','GI','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Granada','GR','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Guadalajara','GU','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Gipuzkoa','GP','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Huelva','HU','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Huesca','HS','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Jaen','JA','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('A Coruña','LC','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('La Rioja','LR','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Las Palmas','LP','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Leon','LE','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Lerida','LD','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Lugo','LU','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Madrid','MD','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Malaga','MA','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Murcia','MU','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Navarra','NA','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Ourense','OR','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Palencia','PA','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Pontevedra','PO','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Salamanca','SA','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Segovia','SG','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Sevilla','SE','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Soria','SO','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Tarragona','TA','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Teruel','TE','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Toledo','TO','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Valencia','VC','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Valladolid','VD','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Bizkaia','VI','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Zamora','ZM','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Zaragoza','ZA','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Melilla','ME','ES');
INSERT INTO xcart_states (state, code, country_code) VALUES('Tenerife','TF','ES');
