INSERT INTO xcart_states (state, code, country_code) VALUES ('Antwerpen','ANT','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Brussel - Bruxelles','BRU','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Hainaut','HAI','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Liège','LIE','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Limburg','LIM','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Luxembourg','Lux','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Namur','NAM','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Oost-Vlaanderen','OVL','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Vlaams-Brabant','VBR','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Brabant Wallon','WBR','BE');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West-Vlaanderen','WVL','BE');
