INSERT INTO xcart_states (state, code, country_code) VALUES ('Bedfordshire','BDF','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Berkshire','BER','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Borders','BOR','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Buckinghamshire','BKM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cambridgeshire','CAM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cheshire','CHS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Clwyd','CLW','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cornwall','CON','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Antrim','ANT','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Armagh','ARM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Down','DOW','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Fermanagh','FER','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Londonderry','LDY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Tyrone','TYR','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cumbria','CMA','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Derbyshire','DBY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Devon','DEV','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Dorset','DOR','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Dumfries and Galloway','DGY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Durham','DUR','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Dyfed','DYF','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('East Anglia','EAN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('East Sussex','ESX','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Essex','ESS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('East Yorkshire','EYS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Fife','FIF','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Glamorgan','GLM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Gloucestershire','GLS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Grampian','GRA','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Greater London','GLN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Greater Manchester','GMN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Gwent','GWE','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Gwynedd','GWN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Hampshire','HAM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Herefordshire','HEF','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Hertfordshire','HRT','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Highlands and Islands','HAL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isles of Scilly','IOS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Wight','IOW','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Inner London','ILN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Kent','KEN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Lancashire','LAN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Leicestershire','LEC','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Lincolnshire','LIN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Lothian','LTN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Mid Glamorgan','MGL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Merseyside','MRS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Norfolk','NFK','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('North Yorkshire','NYK','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Northamptonshire','NTH','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Northumberland','NBL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Nottinghamshire','NTT','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Oxfordshire','OXF','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Powys','POW','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Rutland','RUT','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Shropshire','SHR','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Somerset','SOM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('South Yorkshire','SYS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Staffordshire','STS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Strathclyde','SCL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Suffolk','SFK','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Surrey','SRY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Tyne and Wear','TAW','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Tayside','TYS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Tees Valley','TVL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Warwickshire','WAR','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Glamorgan','WGM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Midlands','WML','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Sussex','WSX','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Yorkshire','WYS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Wiltshire','WIL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Worcestershire','WOR','GB');
